name: Build and Publish RFBC BRL Station Angular App

on:
    workflow_dispatch:
            
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                always-auth: true
                node-version: '20'
                registry-url: 'https://registry.npmjs.org/'
              
            - name: Install Angular
              run: |
                npm install -g @angular/cli

            - name: Install dependencies
              run: |
                cd brlstation
                npm install
                
            - name: Build Angular App
              run: |
                cd brlstation
                ng build --base-href /angular/brlstation/
                
            - name: Publish Build Files to Github Packages
              run: |
                cd brlstation
                npm publish --provenance --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            
        
